name: Update the Veracode CLI

on:
  schedule:
      - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update-cli:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Update Veracode CLI to latest version
        run: |
          cd helper/cli
          cliFile=$(ls -1 . | head -n 1)
          echo "Filename: $cliFile"
          IFS="_"
          read -ra local_version <<< "$cliFile"
          echo "Local version: $local_version[1]"
          curl -sSO https://tools.veracode.com/veracode-cli/LATEST_VERSION
          latest_version=$(<"LATEST_VERSION")
          echo "latest_version: $latest_version"
          if [ "$local_version[1]" = "$latest_version" ]; then
            echo "We already have the current version - nothing to do here"
          else
            echo "There is a new version we need to downlaod"
          fi



#      - name: commit back to repo
#        run: |
#             git config --global user.name 'veracode'
#             git config --global user.email 'cli@veracode.com'
#             git add -A
#             git commit -am "New Plugin Version"
#             git push --verbose
