name: Veracode Static Pipeline Scanner

on:
  workflow_call:
    inputs:
      policy_name:
        required: true
        type: string

  
jobs:
  pipeline_scan:
    runs-on: ubuntu-latest
    name: pipeline scan
    permissions:
        issues: write

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      # get the compiled binary from a previous job
      - name: get archive
        uses: actions/download-artifact@v3
        with:
          name: veracode-artifact
          path: ./veracode_artifact_directory
      
      - name: Get the name of the downloaded files
        run: |
          artifact_file=$(ls -1 ./veracode_artifact_directory | head -n 1)
          echo "veracode_artifact=$artifact_file" >> $GITHUB_ENV

      # run the pipeline scan action
      - name: Veracode Pipeline-Scan
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.10
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          veracode_policy_name: ${{ inputs.policy_name }}
          file: ./veracode_artifact_directory/${{ env.veracode_artifact }}
          fail_build: false

      #- name: import-issues
            #- name: get scan results
            #  uses: actions/download-artifact@v3
            #  with:
            #    name: "Veracode Pipeline-Scan Results"
      - name: Convert pipeline scan output to SARIF format
        id: convert
        uses: Veracode/veracode-pipeline-scan-results-to-sarif@addWorkflowAppSupport
        with:
          pipeline-results-json: filtered_results.json
          output-results-sarif: veracode-results.sarif
          repo_owner: ${{ inputs.repositroy_owner }}
          repo_name: ${{ inputs.repositroy_name }}
          commitSHA: ${{ inputs.commit_sha }}
          ref: 'refs/heads/myBranch'
          githubToken: ${{ github.event.client_payload.token }}
