name: Veracode Build Java Maven Application

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      ref:
        required: true
        type: string
      token:
        required: true
        type: string
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}
    - uses: actions/checkout@v3
      with:
        path: 'veracode-helper'
    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: oracle
    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    - name: Package the appliccation
      env:
        VERACODE_API_KEY_ID: '${{ secrets.VERACODE_API_ID }}'
        VERACODE_API_KEY_SECRET: '${{ secrets.VERACODE_API_KEY }}'
      run: |
        ls -la
        cd veracode-helper/helper/cli
        chmod +x install.sh
        env
        ./install.sh system
        cd /home/runner/work/veracode/veracode/
        echo "cat /opt/veracode/2.9.1/veracode"
        cat /opt/veracode/2.9.1/veracode
        echo "cat /usr/local/bin/veracode/"
        cat /usr/local/bin/veracode
        echo "ls -la /opt/veracode/2.9.1"
        ls -la /opt/veracode/2.9.1
        echo "ls -la"
        ls -la
        veracode-helper/helper/cli/veracode package --source . --output veracode-artifacts --trust
        
      

        
    - uses: actions/upload-artifact@v3
      with:
        name: veracode-artifact
        path: target/${{ env.veracode_artifact }}
